name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetingd
        run: echo "hello there"!
      - name: Print bye
        run: echo "bye bye"
